name: Update Submodule Daily

on:
  schedule:
    # 매일 한국 시간 자정 (UTC 15:00)
    - cron: '0 15 * * *'
  workflow_dispatch: # 수동 실행도 가능하도록

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update submodule to latest
        run: |
          git submodule update --init --recursive
          git submodule update --remote --merge
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: update submodule to latest commit"
          git push
      
      - name: Deploy to Cloudflare Workers
        if: steps.check_changes.outputs.changes == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy